### ISSUE TITLE
Add ped disable pop density

### ISSUE THREAD

**Issue by Daibolik** [justSalkin/juSa_static_NPCs#3]
Hello i have your script wioth the popdensity
i add the horses for the wild horses but when you script is activated all wild ped like dear and stuff like than dont spawn.

**Comment by justSalkin** [comment]
Do the animals you set with my script juSa_static_NPCs not spawn correctly, or PEDs of another script? Unfortunately, I can't really help you with another script. If you tell me the name of the other script, I'll be happy to point out that problems can arise there.

**Comment by Daibolik** [comment]
I take this one
https://github.com/kibook/popdensity

Well, I add all the horses for the horse trainer get in the wild, but when I turn on your script and this script all normal PED doesn't spawn.

**Comment by justSalkin** [comment]
ok, thank you. I`ll mention this conflict in my readme.
Unfortunately I dont know, where that issue comes from, so I'm not able to fix it.
